In [3]:
import pandas as pd
import numpy as np

In [5]:

fs_df = pd.read_csv('Data/FS/Food_Security_Data_E_All_Data/Food_Security_Data_E_All_Data.csv',encoding='latin-1')

/var/folders/r1/74s8bhy11bz94lsfxrg5752m0000gn/T/ipykernel_16470/817154024.py:1: DtypeWarning: Columns (16,22,40,46,52,58,70,82,88,94,97,100,103,109,115,118,121,124,127,130,133,136,139,143,145) have mixed types. Specify dtype option on import or set low_memory=False.
  fs_df = pd.read_csv('Data/FS/Food_Security_Data_E_All_Data/Food_Security_Data_E_All_Data.csv',encoding='latin-1')

In [6]:
fs_norm_df = pd.read_csv('Data/FS/Food_Security_Data_E_All_Data_(Normalized)/Food_Security_Data_E_All_Data_(Normalized).csv',encoding='latin-1')

def group_function(x):
    return pd.Series({'Max Year Code': np.max(x['Year Code'])})

group_features = ['Area Code', 'Item Code','Element Code']

grouped_df = fs_norm_df[group_features+['Year Code']].groupby(by = group_features).apply(group_function).reset_index()

fs_norm_df = fs_norm_df.merge(grouped_df, on = group_features, how= 'outer')
fs_norm_df_filtered = fs_norm_df[fs_norm_df['Year Code']==fs_norm_df['Max Year Code']]

excluded_items = [ 'severely food insecure female adults (million) (3-year average)',
 'severely food insecure female adults (million) (annual value)',
 'severely food insecure male adults (million) (3-year average)',
 'severely food insecure male adults (million) (annual value)',
 'severely food insecure people (million) (3-year average)',
 'severely food insecure people (million) (annual value)','Number of children under 5 years affected by wasting (million)',
 'Number of children under 5 years of age who are overweight (modeled estimates) (million)',
 'Number of children under 5 years of age who are stunted (modeled estimates) (million)',
  'Number of severely food insecure female adults (million) (3-year average)',
 'Number of severely food insecure female adults (million) (annual value)',
 'Number of severely food insecure male adults (million) (3-year average)',
 'Number of severely food insecure male adults (million) (annual value)',
 'Number of severely food insecure people (million) (3-year average)',
 'Number of severely food insecure people (million) (annual value)',
  'Number of moderately or severely food insecure female adults (million) (3-year average)',
 'Number of moderately or severely food insecure female adults (million) (annual value)',
 'Number of moderately or severely food insecure male adults (million) (3-year average)',
 'Number of moderately or severely food insecure male adults (million) (annual value)',
 'Number of moderately or severely food insecure people (million) (3-year average)',
 'Number of moderately or severely food insecure people (million) (annual value)',
 'Number of newborns with low birthweight (million)',
 'Number of people undernourished (million) (3-year average)',
 'Prevalence of moderate or severe food insecurity in the rural adult population (percent) (annual value)',
 'Prevalence of moderate or severe food insecurity in the total population (percent) (3-year average)',
 'Prevalence of moderate or severe food insecurity in the total population (percent) (annual value)',
 'Prevalence of moderate or severe food insecurity in the total population (percent) (3-year average)',
 'Prevalence of moderate or severe food insecurity in the total population (percent) (annual value)',
 'Prevalence of moderate or severe food insecurity in the town and semi-dense area adult population (percent) (annual value)',
 'Prevalence of moderate or severe food insecurity in the urban adult population (percent) (annual value)',
  'Prevalence of severe food insecurity in the rural adult population (percent) (annual value)',
 'Prevalence of severe food insecurity in the total population (percent) (3-year average)',
 'Prevalence of severe food insecurity in the total population (percent) (annual value)',
 'Number of women of reproductive age (15-49 years) affected by anemia (million)',
  'Prevalence of severe food insecurity in the total population (percent) (3-year average)',
 'Prevalence of severe food insecurity in the total population (percent) (annual value)',
 'Prevalence of severe food insecurity in the town and semi-dense area adult population (percent) (annual value)',
 'Prevalence of severe food insecurity in the urban adult population (percent) (annual value)',]
fs_norm_df_filtered = fs_norm_df_filtered[~fs_norm_df_filtered.Item.isin(excluded_items)]
fs_norm_df_filtered.to_csv('fs_norm_filtered.csv')

/var/folders/r1/74s8bhy11bz94lsfxrg5752m0000gn/T/ipykernel_16470/3976851348.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = fs_norm_df[group_features+['Year Code']].groupby(by = group_features).apply(group_function).reset_index()

In [7]:
fs_norm_df_filtered

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Year Code,Year,Unit,Value,Flag,Note,Max Year Code
43,1,'051,Armenia,210041,Prevalence of undernourishment (percent) (3-ye...,6121,Value,20212023,2021-2023,%,<2.5,E,NaN,20212023
219,1,'051,Armenia,210091F,Prevalence of moderate or severe food insecuri...,6121,Value,20212023,2021-2023,%,8.5,A,Official estimate integrated with FAO data,20212023
227,1,'051,Armenia,210091F,Prevalence of moderate or severe food insecuri...,61211,Confidence interval: Lower bound,20212023,2021-2023,%,7.4,A,Official estimate integrated with FAO data,20212023
235,1,'051,Armenia,210091F,Prevalence of moderate or severe food insecuri...,61212,Confidence interval: Upper bound,20212023,2021-2023,%,9.5,A,Official estimate integrated with FAO data,20212023
243,1,'051,Armenia,210091M,Prevalence of moderate or severe food insecuri...,6121,Value,20212023,2021-2023,%,7.2,A,Official estimate integrated with FAO data,20212023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283789,9011,'906,Upper-middle-income economies,21057,Average dietary energy requirement (kcal/cap/day),6128,Value,2023,2023,kcal/cap/d,2427,E,NaN,2023
283810,9011,'906,Upper-middle-income economies,21061,Average fat supply (g/cap/day) (3-year average),6123,Value,20202022,2020-2022,g/cap/d,98.3,E,NaN,20202022
283832,9011,'906,Upper-middle-income economies,22000,Dietary energy supply used in the estimation o...,6128,Value,20212023,2021-2023,kcal/cap/d,3262,E,NaN,20212023
283856,9011,'906,Upper-middle-income economies,220001,Dietary energy supply used in the estimation o...,6128,Value,2023,2023,kcal/cap/d,3275,E,NaN,2023
283879,9011,'906,Upper-middle-income economies,22013,"Gross domestic product per capita, PPP, (const...",6126,Value,2022,2022,Int$/cap,21289.1,X,NaN,2022

In [9]:
hces_norm_df = pd.read_csv('Data/HCES/Household_Consumption_and_Expenditure_Surveys_Food_and_Diet_E_All_Data_(Normalized)/Household_Consumption_and_Expenditure_Surveys_Food_and_Diet_E_All_Data_(Normalized).csv',encoding='latin-1')

hces_norm_df.loc[:,'Area'] = hces_norm_df.Survey.apply(lambda x: x.split(' - ')[0])
hces_norm_df.loc[:,'Year Code'] = hces_norm_df.Survey.apply(lambda x: x.split(' - ')[-1])

hces_norm_df.Survey.unique(),hces_norm_df.shape
group_features = ['Area', 'Indicator Code']

grouped_df = hces_norm_df[group_features+['Year Code']].groupby(by = group_features).apply(group_function).reset_index()
grouped_df.to_csv('grouped_df')
hces_norm_df = hces_norm_df.merge(grouped_df, on = group_features, how= 'outer')
hces_norm_df_filtered = hces_norm_df[hces_norm_df['Year Code']==hces_norm_df['Max Year Code']]
hces_norm_df_filtered = hces_norm_df_filtered[hces_norm_df_filtered['Geographic Level']=='National']
hces_norm_df_filtered.to_csv('hces_norm_df_filtered.csv')

/var/folders/r1/74s8bhy11bz94lsfxrg5752m0000gn/T/ipykernel_16470/1913191083.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = hces_norm_df[group_features+['Year Code']].groupby(by = group_features).apply(group_function).reset_index()

In [10]:
df = pd.read_csv('hces_norm_filtered.csv')
df[df.Area == 'Argentina'].to_csv('hces_norm_filtered_argentina.csv',index=False)

In [2]:
for i in range (220):
    print(f'<option value="{i}">{i}</option>')

<option value="0">0</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
<option value="32">32</option>
<option value="33">33</option>
<option value="34">34</option>
<option value="35">35</option>
<option value="36">36</option>
<option value="37">37</option>
<option value="38">38</option>
<option value="39">39</option>
<option value="40">40</option>
<option value="41">41</option>
<option value="42">42</option>
<option value="43">43</option>
<option value="44">44</option>
<option value="45">45</option>
<option value="46">46</option>
<option value="47">47</option>
<option value="48">48</option>
<option value="49">49</option>
<option value="50">50</option>
<option value="51">51</option>
<option value="52">52</option>
<option value="53">53</option>
<option value="54">54</option>
<option value="55">55</option>
<option value="56">56</option>
<option value="57">57</option>
<option value="58">58</option>
<option value="59">59</option>
<option value="60">60</option>
<option value="61">61</option>
<option value="62">62</option>
<option value="63">63</option>
<option value="64">64</option>
<option value="65">65</option>
<option value="66">66</option>
<option value="67">67</option>
<option value="68">68</option>
<option value="69">69</option>
<option value="70">70</option>
<option value="71">71</option>
<option value="72">72</option>
<option value="73">73</option>
<option value="74">74</option>
<option value="75">75</option>
<option value="76">76</option>
<option value="77">77</option>
<option value="78">78</option>
<option value="79">79</option>
<option value="80">80</option>
<option value="81">81</option>
<option value="82">82</option>
<option value="83">83</option>
<option value="84">84</option>
<option value="85">85</option>
<option value="86">86</option>
<option value="87">87</option>
<option value="88">88</option>
<option value="89">89</option>
<option value="90">90</option>
<option value="91">91</option>
<option value="92">92</option>
<option value="93">93</option>
<option value="94">94</option>
<option value="95">95</option>
<option value="96">96</option>
<option value="97">97</option>
<option value="98">98</option>
<option value="99">99</option>
<option value="100">100</option>
<option value="101">101</option>
<option value="102">102</option>
<option value="103">103</option>
<option value="104">104</option>
<option value="105">105</option>
<option value="106">106</option>
<option value="107">107</option>
<option value="108">108</option>
<option value="109">109</option>
<option value="110">110</option>
<option value="111">111</option>
<option value="112">112</option>
<option value="113">113</option>
<option value="114">114</option>
<option value="115">115</option>
<option value="116">116</option>
<option value="117">117</option>
<option value="118">118</option>
<option value="119">119</option>
<option value="120">120</option>
<option value="121">121</option>
<option value="122">122</option>
<option value="123">123</option>
<option value="124">124</option>
<option value="125">125</option>
<option value="126">126</option>
<option value="127">127</option>
<option value="128">128</option>
<option value="129">129</option>
<option value="130">130</option>
<option value="131">131</option>
<option value="132">132</option>
<option value="133">133</option>
<option value="134">134</option>
<option value="135">135</option>
<option value="136">136</option>
<option value="137">137</option>
<option value="138">138</option>
<option value="139">139</option>
<option value="140">140</option>
<option value="141">141</option>
<option value="142">142</option>
<option value="143">143</option>
<option value="144">144</option>
<option value="145">145</option>
<option value="146">146</option>
<option value="147">147</option>
<option value="148">148</option>
<option value="149">149</option>
<option value="150">150</option>
<option value="151">151</option>
<option value="152">152</option>
<option value="153">153</option>
<option value="154">154</option>
<option value="155">155</option>
<option value="156">156</option>
<option value="157">157</option>
<option value="158">158</option>
<option value="159">159</option>
<option value="160">160</option>
<option value="161">161</option>
<option value="162">162</option>
<option value="163">163</option>
<option value="164">164</option>
<option value="165">165</option>
<option value="166">166</option>
<option value="167">167</option>
<option value="168">168</option>
<option value="169">169</option>
<option value="170">170</option>
<option value="171">171</option>
<option value="172">172</option>
<option value="173">173</option>
<option value="174">174</option>
<option value="175">175</option>
<option value="176">176</option>
<option value="177">177</option>
<option value="178">178</option>
<option value="179">179</option>
<option value="180">180</option>
<option value="181">181</option>
<option value="182">182</option>
<option value="183">183</option>
<option value="184">184</option>
<option value="185">185</option>
<option value="186">186</option>
<option value="187">187</option>
<option value="188">188</option>
<option value="189">189</option>
<option value="190">190</option>
<option value="191">191</option>
<option value="192">192</option>
<option value="193">193</option>
<option value="194">194</option>
<option value="195">195</option>
<option value="196">196</option>
<option value="197">197</option>
<option value="198">198</option>
<option value="199">199</option>
<option value="200">200</option>
<option value="201">201</option>
<option value="202">202</option>
<option value="203">203</option>
<option value="204">204</option>
<option value="205">205</option>
<option value="206">206</option>
<option value="207">207</option>
<option value="208">208</option>
<option value="209">209</option>
<option value="210">210</option>
<option value="211">211</option>
<option value="212">212</option>
<option value="213">213</option>
<option value="214">214</option>
<option value="215">215</option>
<option value="216">216</option>
<option value="217">217</option>
<option value="218">218</option>
<option value="219">219</option>